version: '3'

services:
  frontend:
    image: izabayo7/user-account-mis:latest
    build: ./client/
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000

  backend:
    image: izabayo7/user-account-mis-api:latest
    build: ./user-account-management/
    ports:
      - 5000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:irembo@2020@db:5432/userAccountMis
      - JWT_SECRET=P538uCvyBN400eJkywSywA#NKWOuf0EQMHVttDf54kWmLRA8$t
      - userProfilePicturesPath=/opt/testing/profiles
      - userVerificationFilesPath=/opt/testing/verificationFiles
      - userVerificationFilesPath=/opt/testing/verificationFiles
      - templateId=
      - SEND_GRID_KEY=
      - fromEmail=
      - FRONTEND_URL=http://frontend:3000
  db:
    image: izabayo7/user-account-mis-db:latest
    build: ./deploy/db/
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: irembo@2020
      POSTGRES_DB: userAccountMis
    volumes:
      - './data:/var/lib/postgresql/data '

  nginx:
    image: izabayo7/user-account-mis-nginx:latest
    build: ./deploy/nginx/
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
  # dev:
  #   container_name: backend_api_dev
  #   image: backend-api-dev:1.0.0
  #   build:
  #     context: ./user-account-management
  #     target: development
  #     dockerfile: Dockerfile
  #   command: npm run start:debug
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  # prod:
  #   container_name: backend_api_prod
  #   image: backend-api-prod:1.0.0
  #   build:
  #     context: ./user-account-management
  #     target: production
  #     dockerfile: Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped

networks:
  nesjs-network:
