version: '3'

services:
  frontend:
    image: izabayo7/user-account-mis:latest
    build:
      context: ./client/
      args:
        - VITE_API_URL=$VITE_API_URL
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    image: izabayo7/user-account-mis-api:latest
    build:
      context: ./user-account-management/
      args:
        - FILE_UPLOAD_PATH=$FILE_UPLOAD_PATH
    ports:
      - 5000:3000
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - backend:${FILE_UPLOAD_PATH}
  db:
    image: izabayo7/user-account-mis-db:latest
    build: ./deploy/db/
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: izabayo7/user-account-mis-nginx:latest
    build: ./deploy/nginx/
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  postgres:
    name: nest-prisma-docker-db
  backend:
    name: nest-docker-storage-backend
